#!/bin/bash

echo "🚀 Boutique Vêtements - Setup Guide"
echo "===================================="
echo ""
echo "1. Configurez les variables d'environnement"
echo "   cp .env.local.example .env.local"
echo "   Puis éditez le fichier avec vos données Supabase"
echo ""
echo "2. Créez les tables dans Supabase SQL Editor"
echo "   Voir README_SETUP.md pour le SQL"
echo ""
echo "3. Créez un compte admin"
echo "   Allez sur: https://app.supabase.com"
echo "   Puis Authentication > Add user"
echo ""
echo "4. Lancez le serveur"
echo "   npm run dev"
echo ""
echo "5. Accédez aux sites"
echo "   Client: http://localhost:3000"
echo "   Admin:  http://localhost:3000/admin/login"
echo ""
echo "✅ Prêt à commencer!"
